[build-system]
build-backend = "hatchling.build"
requires = [
    "hatchling",
]

[project]
name = "aa-payout"
description = "Fleet loot valuation and payout system for Alliance Auth"
readme = "README.md"
keywords = [
    "allianceauth",
    "eveonline",
    "payout",
    "fleet",
]
license = { file = "LICENSE" }
authors = [
    { name = "Guarzo", email = "guarzo.eve@gmail.com" },
]
requires-python = ">=3.10"
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dynamic = [
    "version",
]
dependencies = [
    "allianceauth>=4.3.1,<5",
    "django-esi>=5.0.0",
    "django-eveuniverse>=1.6.0",
    "requests>=2.28.0",
]
urls.Changelog = "https://github.com/guarzo/aa-payout/blob/master/CHANGELOG.md"
urls."Issue / Bug Reports" = "https://github.com/guarzo/aa-payout/issues"

[tool.hatch.version]
path = "aapayout/__init__.py"

[tool.hatch.build]
include = [
    "/aapayout",
]
